### PR TITLE
Drcwlt 140

### PR DESCRIPTION
**Pull request by metsawyr**

### CODE REVIEW

**Comment by macolo** [comment]
@metsawyr can you give some context about this merge request?

**Comment by metsawyr** [comment]
@macolo it is related to this bug https://applicature.atlassian.net/browse/DRCWLT-140

**Comment by macolo** [comment]
@metsawyr thank you, would you be able to copy and paste the content of DRCWLT-140 here, as your JIRA instance is non-public?

Could you also send a pull request towards stage (you requested a pull towards master). Many thanks.

**Comment by metsawyr** [comment]
@macolo it's not yet confirmed by QA. If these changes help, I will create second pull request.

**Comment by metsawyr** [comment]
@macolo 
Description
1) Transaction of 0.01DRC to wallet 0xb34e8886f5516c3f46a22bd4af7103ff3e156f43
https://prnt.sc/ichadj - data from backend is different

2) When you send DRC, value in the transactions window is shown in ETH https://prnt.sc/ic1imn

**Comment by macolo** [comment]
@metsawyr I am closing this in favour of https://github.com/darico-coin/darico-wallet/pull/42

**Pull request closed without merging**
